services:
  github:
    image: ghcr.io/github/github-mcp-server
    profiles: ["git", "github", "repo"]
    container_name: github
    stdin_open: true # docker run -i
    tty: true # docker run -t
    labels:
      traefik.enable: true
      # Host(`mcp.${DOMAIN:-localhost}`) && PathPrefix(`/github`)
      traefik.http.routers.github.rule: PathPrefix(`/github`)
    environment:
      GITLAB_API_URL: https://gitlab.com/api/v4
      GITHUB_PERSONAL_ACCESS_TOKEN: "op://Developer/zed-github-mcp/token"
