networks:
  n8n:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ["n8n"]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER:-op://Developer/postgres/username}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-op://Developer/postgres/password}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-op://Developer/n8n/encryption_key}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET:-op://Developer/n8n/jwt_secret}
    - OLLAMA_HOST=${OLLAMA_HOST:-ollama:11434}
  env_file:
    - path: ${XDG_CONFIG_HOME:-$HOME/.config}/docker/config/n8n.env
      required: false

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    profiles: ["core", "n8n"]
    networks: ["n8n"]
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-op://Developer/postgres/username}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-op://Developer/postgres/password}
      - POSTGRES_DB=${POSTGRES_DB:-op://Developer/postgres/database}
    volumes:
      - ${XDG_DATA_HOME:-$HOME/.local/share}/postgres/n8n:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    profiles: ["core", "n8n"]
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/data/credentials && n8n import:workflow --separate --input=/data/workflows"
    volumes:
      - ${XDG_CONFIG_HOME:-$HOME/.config}/mcp/n8n/data:/data
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    profiles: ["core", "n8n"]
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - ${XDG_CONFIG_HOME:-$HOME/.config}/mcp/n8n:/home/node/.n8n
      - ${XDG_DATA_HOME:-$HOME/.local/share}/mcp/n8n/data:/data
      - ${XDG_DATA_HOME:-$HOME/.local/share}/mcp/n8n/data/shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    profiles: ["core", "n8n"]
    networks: ["n8n"]
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ${XDG_DATA_HOME:-$HOME/.local/share}/mcp/qdrant/n8n:/qdrant/storage
