services:
  aws-core:
    image: mcp/aws-core-mcp-server
    profiles: ["project-iac", "mcp-project", "mcp"]
    networks:
      - backend        # MCP backend services network
    labels:
      traefik.enable: true
      traefik.docker.network: backend
      traefik.http.routers.aws-core.rule: PathPrefix(`/aws/core`)

