services:
  aws-tf:
    image: mcp/aws-terraform
    profiles: ["project-iac", "mcp-project", "mcp"]
    networks:
      - backend        # MCP backend services network
    labels:
      traefik.enable: true
      traefik.docker.network: backend
      traefik.http.routers.aws-terraform.rule: PathPrefix(`/aws/tf`)

