services:
  aws-api:
    image: mcp/aws-api-mcp-server
    profiles: ["aws"]
    domainname: aws-api.mcp.${DOMAIN:-localhost}
    networks:
      - backend        # MCP backend services network
    labels:
      traefik.enable: true
      traefik.docker.network: backend
      traefik.http.routers.aws-api.rule: PathPrefix(`/aws/api`)

