services:
  terraform:
    image: hashicorp/terraform-mcp-server
    profiles: ["project-iac", "mcp-project", "mcp"]
    networks:
      - backend        # MCP backend services network
    labels:
      traefik.enable: true
      traefik.docker.network: backend
      traefik.http.routers.terraform.rule: PathPrefix(`/terraform`)

