services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    profiles: ["ollama"]
    networks: ["global"]
    restart: unless-stopped
    ports:
      - ${OLLAMA_PORT:-11434}:11434
    volumes:
      - ${XDG_DATA_HOME:?err_xdg_data_home}/mcp/ollama:/root/.ollama
    labels:
      traefik.enable: true
      traefik.http.services.ollama.loadbalancer.server.port: 11434
      traefik.http.routers.ollama.rule: Host(`llm.${DOMAIN:-localhost}`)
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash",
          "-c",
          "'cat < /dev/null > /dev/tcp/localhost/11434'",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
